-- Vestiaire universel (source des 4 capsules saisonnières, specs du 12/08/2026).
-- La table a été créée manuellement dans l'Éditeur SQL Supabase ; ce fichier
-- documente son schéma dans l'historique de migrations (create table if not
-- exists, sans effet si elle existe déjà) et ajoute les colonnes manquantes
-- par rapport au moteur de règles déjà implémenté côté app (add column if
-- not exists, additif et idempotent — sûr à rejouer sur la table existante).

create table if not exists public.vestiaire_universel (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  category text null,
  url_image text null,
  styles text null,
  morphologies text null,
  colorimetrie text null,
  meteo_min_temp integer null,
  meteo_max_temp integer null,
  resiste_pluie boolean null,
  saison_capsule text null,
  est_basique_capsule boolean null,
  constraint vestiaire_universel_pkey primary key (id)
);

-- Nom de la pièce — affiché partout côté app (Dressing, Tenue du jour, détail
-- pièce). Sans ce champ l'app n'a rien de textuel à montrer pour une pièce du
-- vestiaire universel.
alter table public.vestiaire_universel add column if not exists name text not null default '';

-- Sous-type — nécessaire à R-B6 (baskets non éligibles selon l'occasion),
-- R-B10 (chemise/chemisier incompatibles), R-B12/R-B13 (chaussures
-- d'intérieur, symétriques). Facultatif à l'exception des chaussures
-- (contrainte appliquée côté app, pas en base, comme pour le dressing réel).
alter table public.vestiaire_universel add column if not exists sous_type text null;

-- Niveau de formalité — nécessaire à R-B2, R-B3, R-B6, R-B11. Enum à 4
-- valeurs alignée sur le brief technique (section 1 du brief moteur de règles).
alter table public.vestiaire_universel add column if not exists niveau_formalite text null;
alter table public.vestiaire_universel
  drop constraint if exists vestiaire_universel_niveau_formalite_check;
alter table public.vestiaire_universel
  add constraint vestiaire_universel_niveau_formalite_check
  check (niveau_formalite is null or niveau_formalite in ('sport', 'decontracte', 'business_casual', 'habille'));

-- Rôle de superposition — nécessaire à R-B8 (layering incohérent) et R-S11/
-- R-S12 (bonus et suggestion de layering). Concerne uniquement les catégories
-- hauts/pulls_gilets côté app ; laissé nullable ici, sans effet ailleurs.
alter table public.vestiaire_universel add column if not exists role_piece text null;
alter table public.vestiaire_universel
  drop constraint if exists vestiaire_universel_role_piece_check;
alter table public.vestiaire_universel
  add constraint vestiaire_universel_role_piece_check
  check (role_piece is null or role_piece in ('base', 'calque', 'piece_unique'));

-- Couleur — nécessaire à R-S1 (sobriété chromatique), R-S2 (harmonie),
-- R-S6 (cohérence chaussures/tenue), R-S7 (compétition sac/chaussures), et à
-- l'affichage (pastille couleur) quand url_image est absente.
alter table public.vestiaire_universel add column if not exists couleur_dominante text null;
alter table public.vestiaire_universel add column if not exists hex text null;

-- Genre — exclut les pièces féminines des capsules homme (même logique que
-- CatalogItem.genre côté app aujourd'hui).
alter table public.vestiaire_universel add column if not exists genre text null default 'unisexe';
alter table public.vestiaire_universel
  drop constraint if exists vestiaire_universel_genre_check;
alter table public.vestiaire_universel
  add constraint vestiaire_universel_genre_check
  check (genre is null or genre in ('femme', 'unisexe'));

-- Matière — nécessaire à R-S8 (variété de matières).
alter table public.vestiaire_universel add column if not exists matiere text null;
alter table public.vestiaire_universel
  drop constraint if exists vestiaire_universel_matiere_check;
alter table public.vestiaire_universel
  add constraint vestiaire_universel_matiere_check
  check (matiere is null or matiere in ('Coton', 'Lin', 'Laine', 'Soie', 'Cuir', 'Denim', 'Synthétique'));

-- Lecture publique : le vestiaire universel alimente les capsules par défaut
-- pour toutes les utilisatrices, y compris avant inscription (mode démo).
alter table public.vestiaire_universel enable row level security;
drop policy if exists "Anyone can read vestiaire_universel" on public.vestiaire_universel;
create policy "Anyone can read vestiaire_universel"
  on public.vestiaire_universel for select
  using (true);
