-- Déduplication des visuels du catalogue (recette 18/08/2026 v2) : un asset
-- visuel générique (ex. "ballerines beige femme") est généré une seule fois
-- et réutilisé par tous les articles équivalents, plutôt qu'un image_url par
-- article. vestiaire_universel.visual_asset_id pointe vers l'asset partagé ;
-- les colonnes image_* posées sur vestiaire_universel (migration 0009) sont
-- conservées comme cache dénormalisé pour le frontend (aucun changement côté
-- app nécessaire) — c'est visual_assets qui devient la source de vérité pour
-- la déduplication et le comptage de réutilisation (usage_count).

create table if not exists public.visual_assets (
  id bigint generated by default as identity primary key,
  visual_key text not null unique,
  genre text null,
  category text null,
  sous_type text null,
  couleur text null,
  matiere text null,
  image_url text null,
  image_source text null,
  image_status text not null default 'missing',
  prompt text null,
  generation_model text null,
  generation_quality text null,
  usage_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.visual_assets drop constraint if exists visual_assets_image_status_check;
alter table public.visual_assets add constraint visual_assets_image_status_check
  check (image_status in ('missing', 'generating', 'ready', 'error'));

alter table public.visual_assets drop constraint if exists visual_assets_image_source_check;
alter table public.visual_assets add constraint visual_assets_image_source_check
  check (image_source is null or image_source in ('generated', 'manual', 'affiliate', 'user'));

create index if not exists visual_assets_lookup_idx
  on public.visual_assets (genre, sous_type, couleur);

alter table public.visual_assets enable row level security;
drop policy if exists "Anyone can read visual_assets" on public.visual_assets;
create policy "Anyone can read visual_assets"
  on public.visual_assets for select
  using (true);

drop trigger if exists visual_assets_updated_at on public.visual_assets;
create trigger visual_assets_updated_at
  before update on public.visual_assets
  for each row execute function public.set_updated_at();

-- Lien article -> asset visuel partagé (plusieurs articles peuvent pointer
-- vers le même id).
alter table public.vestiaire_universel add column if not exists visual_asset_id bigint
  references public.visual_assets (id);

-- Suivi des coûts de génération (monitoring) — une ligne par appel API
-- effectivement réalisé (pas par réutilisation de cache, qui ne coûte rien).
create table if not exists public.image_generation_logs (
  id bigint generated by default as identity primary key,
  visual_key text not null,
  model text null,
  quality text null,
  created_at timestamptz not null default now(),
  success boolean not null default false,
  estimated_cost numeric null,
  -- Au-delà du schéma minimal du brief : trace le motif d'échec/plafond
  -- atteint, utile pour le monitoring sans complexifier le reste.
  error text null
);

alter table public.image_generation_logs enable row level security;
drop policy if exists "Anyone can read image_generation_logs" on public.image_generation_logs;
create policy "Anyone can read image_generation_logs"
  on public.image_generation_logs for select
  using (true);
