-- Génération d'images actuelles/tendance (recette 19/08/2026) : un article
-- peut désormais être rattaché à un niveau de tendance (intemporel /
-- contemporain / tendance) et à des instructions de silhouette/détails
-- explicites, avec un échappatoire total (prompt_image_override). Les
-- règles de tendance elles-mêmes vivent dans une table séparée
-- (tendances_mode), par FAMILLE de vêtement (categorie/sous_type/genre),
-- jamais par article — reste légère et maintenable même avec peu de lignes.
-- N'affecte aucune donnée existante : toutes les nouvelles colonnes sont
-- nullables (sauf niveau_tendance, qui a un défaut neutre 'contemporain'
-- appliqué uniquement aux futures lignes, jamais rétroactif).

alter table public.vestiaire_universel add column if not exists niveau_tendance text default 'contemporain';
alter table public.vestiaire_universel add column if not exists silhouette_mode text;
alter table public.vestiaire_universel add column if not exists details_mode text;
alter table public.vestiaire_universel add column if not exists prompt_image_override text;

alter table public.vestiaire_universel drop constraint if exists vestiaire_universel_niveau_tendance_check;
alter table public.vestiaire_universel add constraint vestiaire_universel_niveau_tendance_check
  check (niveau_tendance is null or niveau_tendance in ('intemporel', 'contemporain', 'tendance'));

create table if not exists public.tendances_mode (
  id bigint generated by default as identity primary key,
  categorie text,
  sous_type text,
  genre text,
  saison text,
  annee integer,
  silhouette text,
  coupes text,
  matieres text,
  details text,
  couleurs text,
  elements_a_eviter text,
  actif boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- categorie attendue avec le vocabulaire canonique déjà utilisé partout
-- ailleurs (haut, pull, pantalon, jean, jupe, short, robe, combinaison,
-- veste, manteau, chaussures, sac, bijou, accessoire) et sous_type avec le
-- même vocabulaire que vestiaire_universel.sous_type — c'est sur cette
-- cohérence que repose le matching (cf. _shared/imagePrompt.ts).
create index if not exists tendances_mode_lookup_idx
  on public.tendances_mode (categorie, genre, actif);

alter table public.tendances_mode enable row level security;
drop policy if exists "Anyone can read tendances_mode" on public.tendances_mode;
create policy "Anyone can read tendances_mode"
  on public.tendances_mode for select
  using (true);

drop trigger if exists tendances_mode_updated_at on public.tendances_mode;
create trigger tendances_mode_updated_at
  before update on public.tendances_mode
  for each row execute function public.set_updated_at();
