-- Dressing réel de l'utilisatrice (pièces qu'elle ajoute elle-même, distinct
-- du catalogue vestiaire_universel) — jusqu'ici jamais persisté : tout
-- vivait uniquement dans le state React (useState<AppState>.items) et
-- disparaissait au rechargement de la page. Modèle RLS aligné sur
-- public.profiles (migration 0001) ; set_updated_at() y est déjà défini,
-- réutilisé ici sans redéfinition.
--
-- ⚠️ Ne remplace pas public.pieces (migration 0002) : cette table est un
-- schéma obsolète (11 catégories, pas de colonne worn) jamais branché au
-- code actuel — laissée telle quelle, inutilisée.
--
-- Seuls les champs effectivement renseignés par saveItem (store.tsx) pour
-- une pièce du dressing réel sont persistés ici — tous les autres champs
-- d'Item (rolePiece, styleTags, tonsCouleur, imageUrl...) ne sont peuplés
-- que côté client pour les pièces issues du catalogue, jamais pour une
-- pièce réelle : inutile de leur réserver des colonnes.

create table if not exists public.dressing_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  brand text,
  cat text not null check (cat in (
    'haut', 'pull', 'pantalon', 'jean', 'jupe', 'short', 'robe',
    'combinaison', 'veste', 'manteau', 'chaussures', 'sac', 'bijou', 'accessoire'
  )),
  color text not null,
  hex text not null,
  size text,
  season text not null check (season in ('Printemps / Été', 'Automne / Hiver', 'Toutes saisons')),
  -- Occasions déclarées à l'ajout (plusieurs choix possibles) — liste libre
  -- côté contrainte, comme pour vestiaire_universel.occasions (migration
  -- 0017) : un slug non reconnu est simplement ignoré côté app plutôt que
  -- de bloquer l'insertion.
  occasion text[],
  shoe_type text check (shoe_type is null or shoe_type in (
    'Baskets', 'Bottines', 'Bottes', 'Escarpins', 'Sandales', 'Sandales à talons',
    'Espadrilles', 'Mocassins', 'Ballerines', 'Mules', 'Slingbacks', 'Derbies',
    'Chaussures d''intérieur'
  )),
  matiere text check (matiere is null or matiere in (
    'Coton', 'Lin', 'Laine', 'Soie', 'Cuir', 'Denim', 'Synthétique'
  )),
  coupe text check (coupe is null or coupe = any (array['Serré', 'Ajusté', 'Ample'])),
  sac_type text check (sac_type is null or sac_type in (
    'Sac à main', 'Cabas', 'Bandoulière', 'Pochette', 'Sac à dos'
  )),
  bijou_type text check (bijou_type is null or bijou_type in (
    'Collier', 'Boucles d''oreilles', 'Bracelet', 'Bague', 'Montre'
  )),
  accessoire_type text check (accessoire_type is null or accessoire_type in (
    'Ceinture', 'Foulard', 'Écharpe', 'Chapeau', 'Casquette', 'Lunettes',
    'Collants', 'Chaussettes hautes'
  )),
  subtype text,
  photo_url text,
  -- Jours depuis le dernier port. null = jamais portée. 0 = portée aujourd'hui.
  worn integer,
  -- Valeur de worn avant la dernière action "portée aujourd'hui" — pour Corriger/undo.
  worn_prev integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dressing_items_user_id_idx on public.dressing_items (user_id);

alter table public.dressing_items enable row level security;

create policy "Users can read own dressing items"
  on public.dressing_items for select
  using (auth.uid() = user_id);

create policy "Users can insert own dressing items"
  on public.dressing_items for insert
  with check (auth.uid() = user_id);

create policy "Users can update own dressing items"
  on public.dressing_items for update
  using (auth.uid() = user_id);

create policy "Users can delete own dressing items"
  on public.dressing_items for delete
  using (auth.uid() = user_id);

drop trigger if exists dressing_items_updated_at on public.dressing_items;
create trigger dressing_items_updated_at
  before update on public.dressing_items
  for each row execute function public.set_updated_at();
